name: intelpython3
channels:
  - conda-forge
  - intel
  - defaults
dependencies:
  - asn1crypto=0.24.0=py36_3
  - atomicwrites=1.3.0=py36_1
  - attrs=19.3.0=py_0
  - bzip2=1.0.6=vc14_18
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py36_0
  - cffi=1.11.5=py36_3
  - chardet=3.0.4=py36_3
  - cryptography=2.3=py36_2
  - decorator=4.4.1=py_0
  - icc_rt=2019.5=intel_281
  - idna=2.6=py36_3
  - importlib_metadata=1.1.0=py36_0
  - intel-openmp=2019.5=intel_281
  - intelpython=2019.5=0
  - llvmlite=0.27.1=py36_0
  - mkl=2019.5=intel_281
  - mkl-service=2.3.0=py36_0
  - mkl_fft=1.0.14=py36ha68da19_1
  - mkl_random=1.0.4=py36ha68da19_2
  - more-itertools=7.2.0=py36_0
  - networkx=2.4=py_0
  - numba=0.42.1=np117py36_2
  - numpy-base=1.17.0=py36_13
  - openssl=1.0.2u=hfa6e2cd_0
  - packaging=19.2=py_0
  - pathlib2=2.3.5=py36_0
  - pip=19.1.1=py36_0
  - pluggy=0.13.1=py36_0
  - py=1.8.0=py36_0
  - pycparser=2.18=py36_2
  - pyopenssl=17.5.0=py36_2
  - pyparsing=2.2.0=py36_2
  - pysocks=1.6.7=py36_1
  - pytest=5.2.4=py36_1
  - pytest-mock=1.11.2=py36_0
  - python=3.6.9=5
  - requests=2.20.1=py36_1
  - setuptools=41.0.1=py36_0
  - six=1.12.0=py36_0
  - sqlite=3.28.0=vc14_0
  - tbb=2019.8=vc14_intel_281
  - tbb4py=2019.8=py36_intel_0
  - tcl=8.6.4=vc14_24
  - tk=8.6.4=vc14_29
  - trimesh=3.5.25=py_0
  - urllib3=1.24.1=py36_2
  - vc=14.0=2
  - vs2015_runtime=14.0.25420=intel_2
  - wcwidth=0.1.7=py36_6
  - wheel=0.31.0=py36_3
  - win_inet_pton=1.0.1=py36_4
  - wincertstore=0.2=py36_3
  - xz=5.2.4=vc14_5
  - zipp=0.6.0=py_0
  - zlib=1.2.11=vc14h21ff451_5
  - pip:
    - niftynet==0.6.0
    - miscnn==0.27
    - tensorflow-gpu==1.13.1
    - click==7.0
    - colorama==0.4.1
    - coloredlogs==10.0
    - flask==1.0.2
    - flask-cors==3.0.8
    - flask-json==0.3.3
    - humanfriendly==4.18
    - imageio==2.6.1
    - itsdangerous==1.1.0
    - jinja2==2.10.3
    - markupsafe==1.1.1
    - nibabel==2.4.1
    - numpy==1.16.4
    - pillow==6.2.1
    - pirt==2.1.0
    - pydicom==1.2.2
    - pyopengl==3.1.4
    - pyreadline==2.1
    - python-dotenv==0.10.3
    - pywavelets==1.1.1
    - scikit-image==0.15.0
    - scipy==1.3.0
    - simpleitk==1.2.0
    - visvis==1.12.2
    - werkzeug==0.16.0

